name: OID4VCI document push
on:
  push:
    paths:
      - 'openid-4-verifiable-prentations-1_0.md'

jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Run the build process with Docker
            run: |     
                docker run \
                -v /${{ github.workspace }}:/data danielfett/markdown2rfc \
                openid-4-verifiable-presentations-1_0.md
                
          - uses: actions/upload-artifact@v3
            with:
                # Artifact name
                name: OID4CI # optional
                # Destination path
                path: ./openid-4-verifiable-presentations*.html # optional
